version: "3.8"
services:
  user-service:
    build: ./user-service
    container_name: user_service
    restart: always
    depends_on:
      - postgres_user
    environment:
      DB_HOST: postgres_user
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: users_db
    ports:
      - "3001:3001"

  order-service:
    build: ./order-service
    container_name: order_service
    restart: always
    depends_on:
      - postgres_order
    environment:
      DB_HOST: postgres_order
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: orders_db
    ports:
      - "3002:3002"

  inventory-service:
    build: ./inventory-service
    container_name: inventory_service
    restart: always
    depends_on:
      - mongodb_inventory
    environment:
      DB_HOST: mongodb_inventory
      DB_PORT: 27017
      DB_NAME: inventory_db
    ports:
      - "3003:3003"

  notification-service:
    build: ./notification-service
    container_name: notification_service
    restart: always
    depends_on:
      - rabbitmq
      - kafka
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "3004:3004"
